export const XNEWS_TOOL_NAMES = [
  "xnews_news",
  "xnews_research",
  "xnews_data",
  "xnews_events",
  "xnews_works",
  "xnews_files",
  "xnews_extract",
  "xnews_ocr",
  "xnews_transcribe",
  "xnews_catalog",
] as const;

export type XnewsToolName = (typeof XNEWS_TOOL_NAMES)[number];

export const XNEWS_NEWS_PROVIDERS = [
  "yahoo-finance",
  "google-news",
  "sec-edgar",
  "finviz",
  "bing-news",
  "gdelt",
  "tickertick",
  "hacker-news",
  "yahoo-search",
  "sec-fulltext",
  "sec-current",
  "federal-register",
  "courtlistener",
  "msrb-emma",
  "nasdaq",
  "seeking-alpha",
  "hf-transcripts",
  "marketwatch",
  "wsj",
  "cnbc",
  "pr-newswire",
  "globenewswire",
  "federal-reserve",
  "sec-press",
  "ffiec",
  "fdic",
  "occ",
  "cfpb",
  "coindesk",
  "cointelegraph",
  "benzinga",
  "investing-com",
  "upi",
  "oilprice",
  "nyt",
  "bbc",
  "npr",
  "guardian",
  "ft",
  "economist",
  "fortune",
  "forbes",
  "washington-post",
  "youtube",
  "cftc-cot",
  "ffiec-cdr",
  "dtcc-sdr",
  "arxiv",
  "openalex",
  "bis-research",
  "bis-research-hub",
  "nber",
  "ssrn",
  "crossref",
  "world-bank",
  "biorxiv",
  "medrxiv",
  "europe-pmc",
  "hf-papers",
  "osf-preprints",
  "bis-press",
  "bis-speeches",
  "bcb-news",
  "boj-news",
  "bok-news",
  "rbi-news",
  "bsp-news",
  "hkma-news",
  "rba-news",
  "rbnz-news",
  "banco-de-espana-news",
  "banca-ditalia-news",
  "dnb-news",
  "central-bank-ireland-news",
  "cnb-news",
  "mnb-news",
  "tcmb-news",
  "sarb-news",
  "norges-bank-news",
  "riksbank-news",
  "central-bank-iceland-news",
  "ecb-news",
  "bank-england-news",
  "bank-canada-news",
  "bundesbank-news",
  "snb-news",
  "atlanta-fed-news",
  "richmond-fed-news",
  "dallas-fed-news",
  "fed-board-research",
  "bcb-research",
  "bok-research",
  "hkma-research",
  "ecb-research",
  "bank-canada-research",
  "bundesbank-research",
  "norges-bank-research",
  "snb-research",
  "rba-research",
  "banco-de-espana-research",
  "banca-ditalia-research",
  "dnb-research",
  "ofac",
  "who-outbreaks",
] as const;

export type XnewsNewsProvider = (typeof XNEWS_NEWS_PROVIDERS)[number];

export const XNEWS_RESEARCH_PROVIDERS = [
  "arxiv",
  "openalex",
  "bis-research",
  "bis-research-hub",
  "nber",
  "ssrn",
  "crossref",
  "world-bank",
  "biorxiv",
  "medrxiv",
  "europe-pmc",
  "hf-papers",
  "osf-preprints",
  "fed-board-research",
  "bcb-research",
  "bok-research",
  "hkma-research",
  "ecb-research",
  "bank-canada-research",
  "bundesbank-research",
  "norges-bank-research",
  "snb-research",
  "rba-research",
  "banco-de-espana-research",
  "banca-ditalia-research",
  "dnb-research",
] as const satisfies readonly XnewsNewsProvider[];

export const XNEWS_EVENT_PROVIDERS = [
  "nws-alerts",
  "gdacs",
  "nhc-storms",
  "usgs-volcanoes",
  "noaa-tsunami",
  "glofas-flood",
  "gdelt-events",
  "faa-status",
  "safecast-radiation",
  "sondehub-balloons",
  "wikipedia-congress-edits",
] as const;

export const XNEWS_WORKS_PROVIDERS = [
  "annas-archive",
  "internet-archive",
  "libgen",
  "open-library",
] as const;

export interface XnewsDatasetCapability {
  readonly provider: string;
  readonly dataset: string;
  readonly sourceContextRequired: true;
  readonly sequenced?: true;
}

/** Built-in data-lane factories. Dynamic suffixes are written as `{name}`. */
export const XNEWS_DATASETS = [
  { provider: "caiso-fuel-mix", dataset: "fuel-source", sourceContextRequired: true },
  { provider: "uk-carbon-intensity", dataset: "generation-mix", sourceContextRequired: true },
  { provider: "cdc-wastewater", dataset: "wastewater-activity", sourceContextRequired: true },
  { provider: "cisa-kev", dataset: "known-exploited-vulnerabilities", sourceContextRequired: true },
  { provider: "cftc-cot", dataset: "{report-family}", sourceContextRequired: true },
  { provider: "ffiec-cra", dataset: "{flat-file-kind}-flat-file", sourceContextRequired: true },
  { provider: "us-drought-monitor", dataset: "area-percent", sourceContextRequired: true },
  {
    provider: "dtcc-sdr",
    dataset: "{agency}-{asset-class}-slices",
    sourceContextRequired: true,
    sequenced: true,
  },
  { provider: "dtcc-sdr", dataset: "{agency}-{asset-class}-eod", sourceContextRequired: true },
  { provider: "ffiec-cdr", dataset: "call-single-period", sourceContextRequired: true },
  { provider: "ffiec-002", dataset: "{rssd}", sourceContextRequired: true },
  { provider: "ffiec-census", dataset: "census-flat-file-{year}", sourceContextRequired: true },
  { provider: "ffiec-e16", dataset: "country-exposure", sourceContextRequired: true },
  { provider: "fred", dataset: "{series-id}", sourceContextRequired: true },
  { provider: "ffiec-fry9", dataset: "{report}", sourceContextRequired: true },
  { provider: "grants-gov", dataset: "opportunities", sourceContextRequired: true },
  {
    provider: "hmda",
    dataset: "[nationwide-]aggregations:{year}:{filters}",
    sourceContextRequired: true,
  },
  { provider: "wfp-hungermap", dataset: "food-security", sourceContextRequired: true },
  { provider: "ioda-outages", dataset: "country-outages", sourceContextRequired: true },
  { provider: "nasa-gistemp", dataset: "global-temp-anomaly", sourceContextRequired: true },
  { provider: "ffiec-nic", dataset: "{bulk-product}", sourceContextRequired: true },
  { provider: "noaa-co2", dataset: "co2-trend-global", sourceContextRequired: true },
  { provider: "noaa-oni", dataset: "oceanic-nino-index", sourceContextRequired: true },
  { provider: "ooni-censorship", dataset: "anomaly-aggregation", sourceContextRequired: true },
  { provider: "unhcr-displacement", dataset: "population", sourceContextRequired: true },
  { provider: "usaspending", dataset: "awards", sourceContextRequired: true },
  {
    provider: "wikipedia-congress-edits",
    dataset: "historical-edits",
    sourceContextRequired: true,
  },
  { provider: "wikipedia-pageviews", dataset: "top-articles", sourceContextRequired: true },
  { provider: "world-bank-indicators", dataset: "{indicator}", sourceContextRequired: true },
] as const satisfies readonly XnewsDatasetCapability[];

export interface XnewsCapabilityDefinition<Operation extends string = string> {
  readonly tool: XnewsToolName;
  readonly operations: readonly Operation[];
  readonly description: string;
  readonly finite: boolean;
  readonly runtimeContextOnly?: readonly string[];
}

export const XNEWS_CAPABILITY_REGISTRY = [
  {
    tool: "xnews_news",
    operations: ["company", "topic", "watchlist"],
    description: "Normalized company, topic, and watchlist news envelopes.",
    finite: true,
  },
  {
    tool: "xnews_research",
    operations: ["search"],
    description: "Research-paper retrieval with research-specific filters.",
    finite: true,
  },
  {
    tool: "xnews_data",
    operations: ["fetch"],
    description: "One structured-data release from a host-bound data source.",
    finite: true,
    runtimeContextOnly: ["dataSources"],
  },
  {
    tool: "xnews_events",
    operations: ["snapshot", "across"],
    description: "One active-event snapshot or a cross-source merge.",
    finite: true,
    runtimeContextOnly: ["eventSources"],
  },
  {
    tool: "xnews_works",
    operations: ["search", "across", "resolve_identity"],
    description: "Bibliographic catalog search and identity resolution.",
    finite: true,
    runtimeContextOnly: ["worksSources"],
  },
  {
    tool: "xnews_files",
    operations: ["resolve", "download_file", "download_work"],
    description: "Host-bound work-file discovery and bounded downloads.",
    finite: true,
    runtimeContextOnly: ["workRecords", "workFiles", "mirrors", "credentials"],
  },
  {
    tool: "xnews_extract",
    operations: [
      "text",
      "pdf_text",
      "pdf_images",
      "djvu",
      "xlsx",
      "zip",
      "csv_records",
      "csv_table",
    ],
    description: "Finite text, document, spreadsheet, archive, and CSV parsing.",
    finite: true,
    runtimeContextOnly: ["binaryArtifacts"],
  },
  {
    tool: "xnews_ocr",
    operations: ["images", "pdf"],
    description: "Finite OCR over host-held images or a PDF.",
    finite: true,
    runtimeContextOnly: ["binaryArtifacts", "ocr"],
  },
  {
    tool: "xnews_transcribe",
    operations: ["youtube_captions", "pcm"],
    description: "Finite captions or PCM transcription; live sessions are nodes.",
    finite: true,
    runtimeContextOnly: ["binaryArtifacts", "realtimeAsrBackends"],
  },
  {
    tool: "xnews_catalog",
    operations: [
      "capabilities",
      "providers",
      "datasets",
      "request_data_urls",
      "request_event_urls",
      "request_works_urls",
    ],
    description: "Static capabilities and redacted URL previews for host-bound sources.",
    finite: true,
  },
] as const satisfies readonly XnewsCapabilityDefinition[];

export const XNEWS_OPERATION_REGISTRY = {
  xnews_news: XNEWS_CAPABILITY_REGISTRY[0].operations,
  xnews_research: XNEWS_CAPABILITY_REGISTRY[1].operations,
  xnews_data: XNEWS_CAPABILITY_REGISTRY[2].operations,
  xnews_events: XNEWS_CAPABILITY_REGISTRY[3].operations,
  xnews_works: XNEWS_CAPABILITY_REGISTRY[4].operations,
  xnews_files: XNEWS_CAPABILITY_REGISTRY[5].operations,
  xnews_extract: XNEWS_CAPABILITY_REGISTRY[6].operations,
  xnews_ocr: XNEWS_CAPABILITY_REGISTRY[7].operations,
  xnews_transcribe: XNEWS_CAPABILITY_REGISTRY[8].operations,
  xnews_catalog: XNEWS_CAPABILITY_REGISTRY[9].operations,
} as const satisfies Readonly<Record<XnewsToolName, readonly string[]>>;
